name: Web Tests with Allure

on:
  workflow_dispatch:

permissions:
  contents: write  # needed for gh-pages deploy

env:
  NODE_VERSION: "20"
  TEST_COMMAND: "npm run test:e2e"
  PLATFORM: "web"
  EMAIL_SUBJECT_PREFIX: "Playwright Automation"
  PAGES_BASE_URL: ""

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Load .env.ci without a marketplace action (portable)
      - name: Load .env.ci (shell)
        if: ${{ hashFiles('.env.ci') != '' }}
        run: |
          set -e
          echo "Loading .env.ci..."
          while IFS='=' read -r key value; do
            # skip comments/empty lines
            [[ -z "$key" ]] && continue
            [[ "$key" =~ ^# ]] && continue
            # export into GITHUB_ENV
            echo "$key=${value}" >> "$GITHUB_ENV"
          done < .env.ci

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: |
          npx playwright install
          sudo npx playwright install-deps

      - name: Clean old Allure results and report
        run: rm -rf allure-results allure-report analytics

      - name: Run tests
        run: ${{ env.TEST_COMMAND }}

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

  host:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load .env.ci (shell)
        if: ${{ hashFiles('.env.ci') != '' }}
        run: |
          set -e
          echo "Loading .env.ci..."
          while IFS='=' read -r key value; do
            [[ -z "$key" ]] && continue
            [[ "$key" =~ ^# ]] && continue
            echo "$key=${value}" >> "$GITHUB_ENV"
          done < .env.ci

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Generate Allure report
        run: |
          rm -rf allure-report
          allure generate allure-results --clean -o allure-report
          # ensure GitHub Pages doesn't run Jekyll (which can block assets)
          touch allure-report/.nojekyll

      - name: Ensure analytics store exists
        run: |
          mkdir -p analytics
          test -f analytics/history.json || echo "[]" > analytics/history.json
    
      - name: Build analytics history
        run: |
          node generate-analytics.js
          mkdir -p allure-report/analytics
          cp -f analytics/history.json allure-report/analytics/history.json
        env:
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      
      - name: Copy analytics dashboard into report
        run: |
          mkdir -p allure-report/analytics
          cp -f analytics-dashboard/index.html allure-report/analytics/index.html
          cp -f analytics-dashboard/viewer.js allure-report/analytics/viewer.js

      - name: Add Analytics link into Allure navbar
        run: |
          # copy the injector script
          cp -f analytics-dashboard/inject-analytics.js allure-report/analytics/inject-analytics.js
          # inject a script tag once into index.html (idempotent)
          node - <<'NODE'
          const fs = require('fs');
          const p = 'allure-report/index.html';
          let html = fs.readFileSync(p, 'utf8');
          if (!html.includes('analytics/inject-analytics.js')) {
            html = html.replace('</body>', '  <script src="analytics/inject-analytics.js"></script>\n</body>');
            fs.writeFileSync(p, html);
            console.log('Injected analytics script into index.html');
          } else {
            console.log('Analytics script already present, skipping inject');
          }
          NODE

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report/
          publish_branch: gh-pages
          keep_files: true

      - name: Create Report Summary (Slack optional)
        if: always()
        run: |
          node create-summary.js --platform="${{ env.PLATFORM }}"
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          PAGES_BASE_URL: ${{ env.PAGES_BASE_URL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}

      - name: Export email body
        id: export_email
        run: |
          echo 'EMAIL_BODY<<EOF' >> $GITHUB_ENV
          cat email-body.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      # Guard the email step WITHOUT referencing "secrets" in the if-expression
      # We check only that EMAIL_BODY exists; if creds are missing the action will fail,
      # so we soften with continue-on-error: true. If you want hard fail, remove that line.
      - name: Send email with report URL
        if: ${{ env.EMAIL_BODY != '' }}
        continue-on-error: true
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "${{ env.EMAIL_SUBJECT_PREFIX }} - $(date '+%d-%b-%Y')"
          to: ${{ secrets.EMAIL_RECIPIENT_LIST }}
          cc: ${{ secrets.EMAIL_CC_LIST }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: ${{ env.EMAIL_BODY }}
